name: Sahil-Tea-House-Bot

on:
workflow_dispatch:
schedule:
- cron: '*/30 * * * *'   # runs every 30 minutes

jobs:
run-bot:
runs-on: ubuntu-latest
timeout-minutes: 350

steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '20'

  - name: Install Dependencies
    run: npm install

  - name: Run Bot
    env:
      FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
    run: |
      echo "Starting WhatsApp Bot..."
      node index.js
